import type { Metadata } from "next";
import { Playfair_Display, Mulish } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";

const mulish = Mulish({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900", "1000"],
  variable: "--font-mulish",
});
const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-playfairDisplay",
});

export const metadata: Metadata = {
  title: "Matching Guru",
  description: "Generated by create next app",
  icons: { icon: "/assets/ui/logo.png" },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${mulish.variable} ${playfairDisplay.variable}`}>
        <Header />
        <main className="relative">
        <PageTransition>{children}</PageTransition>
        </main>
      </body>
    </html>
  );
}
