import type { Metadata } from "next";
import { Playfair_Display, Mulish } from "next/font/google";
import "../globals.css";
import { AuthProvider } from "@/app/context/AuthContext";
import { ReactNode } from "react";
import DashboardLayout from "./DashboardLayout";

const mulish = Mulish({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-mulish",
});
const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-playfairDisplay",
});

export const metadata: Metadata = {
  title: "Matching Guru",
  description: "Generated by create next app",
  icons: { icon: "/assets/ui/logo(yy).png" },
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={`${mulish.variable} ${playfairDisplay.variable}`}>
        <AuthProvider>
          <DashboardLayout>{children}</DashboardLayout>
        </AuthProvider>
      </body>
    </html>
  );
}
